### ISSUE TITLE
Low volume

### ISSUE THREAD

**Issue by Aerstme** [afkniladri/Acer-Nitro5-Hackintosh-OC#4]
Hi again

i finally got the wifi working, but now I think the volume is too low in some cases, for example when I receive audio messages from whatsapp or youtube.

There is a way to fix it?

Thanks for all
Regards.

**Comment by 0xNILADRI** [comment]
I tried my best to rectify this issue, unfortunately there's no way to boost the audio output. While using linux I face the same issue but there are numerous ways to fix this; say boost the volume to 150%, since it's not the same with mac os and the community is too small and diverse so there's not much helping hands. Although I don't think there's a solution (I'm satisfied with layout I'd 29), it's just that I rose the white flag. Btw if you come up with something please do share it with us.
