### ISSUE TITLE
Boot Time

### ISSUE THREAD

**Issue by velcis** [afkniladri/Acer-Nitro5-Hackintosh-OC#5]
Hello sir, I figured out the boot is slow, more than a minute. What time of yours?
Everything works good, but in Big Sur I had 8-12 secs boot time, and now more than a minute.

**Comment by 0xNILADRI** [comment]
I booted my device just now and it takes around 15s. Is it slow for the oc boot selector or the operating system boot. Also I don't think it should take a minute on ssd. I would recommend you to clean your EFI folder and place the files again else you can also consider a clean install. Since no one has faced such an issue till now, therefor i'll close the issue. Let me know if it works.
